### ISSUE TITLE
Issues with schedule exceptions and the form with peoples shifts for a specific day

### ISSUE THREAD

**Issue by lukaskom** [jenkys/shiftify#52]
When I change or add an exception for some day and go back to the view with all users for the day with the new or changed exceptions, it doesn't update automatically. I have to go to the side bar menu and select the view again to reload.

Another thing is that I don't see much difference between the red line when there is an exceptionShift from 10:30 - 14:00 and when there is a scheduleShift from 6:00 to 14:00. Please ignore this if it was just some glitch on my phone.

**Comment by liferili** [comment]
Fixed in commit https://github.com/jenkys/shiftify/commit/cb4f8155566c25d2c1d0e8143673e89458d993d5
